# Generated by Django 2.1.1 on 2018-10-18 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subhead',
            field=models.TextField(default=django.utils.timezone.now),
        ),
    ]
