# Generated by Django 2.1.1 on 2018-10-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subhead',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
